// src/components/BadgeLibrary.ts

const BadgeLibrary = {
  'ux-ui-design': {
    label: 'UX/UI Design',
    icon: 'FaPalette',
    colorLight: '#0052CC',
    colorDark: '#82AAFF',
  },
  figma: {
    label: 'Figma',
    icon: 'FaFigma',
    colorLight: '#FF7262',
    colorDark: '#FF9580',
  },
  figjam: {
    label: 'FigJam',
    icon: 'FaPencilAlt',
    colorLight: '#F24E1E',
    colorDark: '#FF855D',
  },
  notion: {
    label: 'Notion',
    icon: 'FaBook',
    colorLight: '#000000',
    colorDark: '#EEEEEE',
  },
  chatgpt: {
    label: 'ChatGPT',
    icon: 'FaRobot',
    colorLight: '#10A37F',
    colorDark: '#6EDBD1',
  },
  'user-research': {
    label: 'User Research',
    icon: 'FaUserFriends',
    colorLight: '#FFB300',
    colorDark: '#FFD54F',
  },
  prototyping: {
    label: 'Prototyping',
    icon: 'FaDraftingCompass',
    colorLight: '#00875A',
    colorDark: '#5CBF8F',
  },
  'iterative-prototyping': {
    label: 'Iterative Prototyping',
    icon: 'FaRedo',
    colorLight: '#6554C0',
    colorDark: '#B8A1F7',
  },
  'user-centered-design': {
    label: 'User-Centered Design',
    icon: 'FaUser',
    colorLight: '#00B8D9',
    colorDark: '#79E2F2',
  },
  accessibility: {
    label: 'Zugängliches Design',
    icon: 'FaUniversalAccess',
    colorLight: '#0052CC',
    colorDark: '#82AAFF',
  },
  react: {
    label: 'React',
    icon: 'FaReact',
    colorLight: '#61DAFB',
    colorDark: '#9EEBF9',
  },
  'styled-components': {
    label: 'Styled Components',
    icon: 'FaPalette',
    colorLight: '#DB7093',
    colorDark: '#F4A6C1',
  },
  'component-reusability': {
    label: 'Component Reusability',
    icon: 'FaCubes',
    colorLight: '#403294',
    colorDark: '#A69EDA',
  },
  'state-management': {
    label: 'State Management',
    icon: 'FaTasks',
    colorLight: '#4C9AFF',
    colorDark: '#A0C4FF',
  },
  'dynamic-uis': {
    label: 'Dynamic UIs',
    icon: 'FaCode',
    colorLight: '#6554C0',
    colorDark: '#B8A1F7',
  },
  'api-integration': {
    label: 'API Integration',
    icon: 'FaPlug',
    colorLight: '#00BFA5',
    colorDark: '#5DF2D9',
  },
  'json-handling': {
    label: 'JSON Handling',
    icon: 'FaFileCode',
    colorLight: '#FF8B00',
    colorDark: '#FFBE65',
  },
  'dynamic-styling': {
    label: 'Dynamic Styling',
    icon: 'FaBrush',
    colorLight: '#E3008C',
    colorDark: '#FF66B2',
  },
  'structured-development': {
    label: 'Structured Development',
    icon: 'FaFolderOpen',
    colorLight: '#6554C0',
    colorDark: '#B8A1F7',
  },
  efficiency: {
    label: 'Efficiency',
    icon: 'FaBolt',
    colorLight: '#FFAB00',
    colorDark: '#FFD65A',
  },
  scalability: {
    label: 'Scalability',
    icon: 'FaChartLine',
    colorLight: '#36B37E',
    colorDark: '#77D39F',
  },
  'ai-support': {
    label: 'AI Support',
    icon: 'FaRobot',
    colorLight: '#00BFA5',
    colorDark: '#5DF2D9',
  },
  flexibility: {
    label: 'Flexibility',
    icon: 'FaTools',
    colorLight: '#00A991',
    colorDark: '#5EDBC7',
  },
  python: {
    label: 'Python 3.10+',
    icon: 'FaPython',
    colorLight: '#306998',
    colorDark: '#6FAED6',
  },
  tdd: {
    label: 'TDD',
    icon: 'FaBug',
    colorLight: '#FF5630',
    colorDark: '#FF8A70',
  },
  'domain-driven-design': {
    label: 'Domain Driven Design',
    icon: 'FaProjectDiagram',
    colorLight: '#6554C0',
    colorDark: '#B8A1F7',
  },
  'user-friendly-gui': {
    label: 'User-Friendly GUI',
    icon: 'FaMousePointer',
    colorLight: '#36B37E',
    colorDark: '#77D39F',
  },
  'markdown-export': {
    label: 'Markdown Export',
    icon: 'FaFileAlt',
    colorLight: '#6554C0',
    colorDark: '#B8A1F7',
  },
  'token-export': {
    label: 'Token Export',
    icon: 'FaFileAlt',
    colorLight: '#6554C0',
    colorDark: '#B8A1F7',
  },
  'gitignore-support': {
    label: '.gitignore Support',
    icon: 'FaShieldAlt',
    colorLight: '#253858',
    colorDark: '#6E7E8E',
  },
  'modular-design': {
    label: 'Modular Design',
    icon: 'FaCogs',
    colorLight: '#FF8B00',
    colorDark: '#FFBE65',
  },
  'cli-tool': {
    label: 'CLI Tool',
    icon: 'FaTerminal',
    colorLight: '#333333',
    colorDark: '#BBBBBB',
  },
  'clean-code': {
    label: 'Clean Code',
    icon: 'FaCode',
    colorLight: '#42526E',
    colorDark: '#9BB1C8',
  },
  automation: {
    label: 'Automation',
    icon: 'FaCogs',
    colorLight: '#00BFA5',
    colorDark: '#5DF2D9',
  },
  'drag-and-drop': {
    label: 'Drag & Drop',
    icon: 'FaMousePointer',
    colorLight: '#0052CC',
    colorDark: '#82AAFF',
  },
  'project-templates': {
    label: 'Project Templates',
    icon: 'FaFolderOpen',
    colorLight: '#403294',
    colorDark: '#A69EDA',
  },
  'skryper-integration': {
    label: 'Skryper Integration',
    icon: 'FaPuzzlePiece',
    colorLight: '#00875A',
    colorDark: '#5CBF8F',
  },
  'svg-swatches': {
    label: 'SVG swatches',
    icon: 'FaShapes',
    colorLight: '#FF5630',
    colorDark: '#FF8A70',
  },
  'light-dark-mode': {
    label: 'Light/Dark Mode',
    icon: 'FaMoon',
    colorLight: '#6554C0',
    colorDark: '#B8A1F7',
  },
  'design-system': {
    label: 'Design System',
    icon: 'FaPaintBrush',
    colorLight: '#36B37E',
    colorDark: '#77D39F',
  },
  'windows-first': {
    label: 'Windows First',
    icon: 'FaWindows',
    colorLight: '#00A4EF',
    colorDark: '#72C9FF',
  },
  java: {
    label: 'Java',
    icon: 'FaJava',
    colorLight: '#007396',
    colorDark: '#68AFCB',
  },
  'spring-boot': {
    label: 'Spring Boot',
    icon: 'FaLeaf',
    colorLight: '#6DB33F',
    colorDark: '#97D07C',
  },
  'spring-security': {
    label: 'Spring Security',
    icon: 'FaLock',
    colorLight: '#008562',
    colorDark: '#5EDBC7',
  },
  mongodb: {
    label: 'MongoDB',
    icon: 'FaDatabase',
    colorLight: '#47A248',
    colorDark: '#86C87E',
  },
  'rest-api': {
    label: 'REST API',
    icon: 'FaNetworkWired',
    colorLight: '#0052CC',
    colorDark: '#82AAFF',
  },
  'jwt-auth': {
    label: 'JWT Auth',
    icon: 'FaKey',
    colorLight: '#FF8B00',
    colorDark: '#FFBE65',
  },
  docker: {
    label: 'Docker',
    icon: 'FaDocker',
    colorLight: '#2496ED',
    colorDark: '#6EBFFF',
  },
  'responsive-design': {
    label: 'Responsive Design',
    icon: 'FaMobileAlt',
    colorLight: '#00B8D9',
    colorDark: '#79E2F2',
  },
  'ux-ui-best-practices': {
    label: 'UX/UI Best Practices',
    icon: 'FaPalette',
    colorLight: '#0052CC',
    colorDark: '#82AAFF',
  },
  gamification: {
    label: 'Gamification',
    icon: 'FaTrophy',
    colorLight: '#FFAB00',
    colorDark: '#FFD65A',
  },
}

export default BadgeLibrary
